import './globals.css'
import { Roboto  } from 'next/font/google'

import { ReduxProvider } from './redux/provider'
import Navbar from './components/Navbar/Navbar'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Medetcan Diler | Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="main">
          <div className="gradient"></div>
        </div>
        <ReduxProvider>
          <div className="app font-serif">
            <Navbar />
            {children}
          </div>
        </ReduxProvider>
      </body>
    </html>
  )
}
